# Generated by Django 2.0.6 on 2018-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
